[build]
  publish = "."

[[redirects]]
  from = "/locations/:slug"
  to = "/location.html?loc=:slug"
  status = 200

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
